export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const TOGGLE_USER_VISIBILITY = 'TOGGLE_USER_VISIBILITY'
export const SET_USERS = 'SET_USERS'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'